[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  # Eliminamos el SKIP para que el motor funcione

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/super-yachts"
  to = "/super-yachts-sails-2"
  status = 301

[[redirects]]
  from = "/spinnakers-crucero"
  to = "/spinnakers-simetricos-y-asimetricos-de-crucero"
  status = 301

# ... (Mantén aquí el resto de tus redireccionamientos tal cual los tenías)
